from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from core import views


urlpatterns = [
    path("login", views.login_page, name="login_page"),
    path("uitnodiging/<str:invite_token>", views.invite_accept_page, name="invite_accept_page"),
    path("logout", views.logout_page, name="logout_page"),
    path("", views.index, name="index"),
    path("management", views.management_page, name="management_page"),
    path("management/api", views.api_management_page, name="api_management_page"),
    path("materialen", views.materialen_page, name="materialen_page"),
    path(
        "materialen/clubs/export-pdf",
        views.materialen_all_clubs_export_pdf,
        name="materialen_all_clubs_export_pdf",
    ),
    path(
        "materialen/clubs/<int:club_id>/export-pdf",
        views.materialen_club_export_pdf,
        name="materialen_club_export_pdf",
    ),
    path("begroting", views.budget_page, name="budget_page"),
    path("management/begroting", views.budget_page, name="budget_page_alias"),
    path("aanmeldingen", views.registrations_page, name="registrations_page"),
    path(
        "aanmeldingen/<path:product_key>/teamindeling-export",
        views.export_registration_team_assignment,
        name="export_registration_team_assignment",
    ),
    path("aanmeldingen/<path:product_key>", views.registrations_detail_page, name="registrations_detail_page"),
    path("leads", views.leads_page, name="leads_page"),
    path("financien", views.financien_page, name="financien_page"),
    path("financien/automatisch-facturen", views.automatic_invoices_page, name="automatic_invoices_page"),
    path("omzet", views.revenue_home_page, name="revenue_home_page"),
    path("omzet/totaal", views.revenue_total_page, name="revenue_total_page"),
    path("omzet/per-maand", views.revenue_monthly_page, name="revenue_monthly_page"),
    path("omzet/winst", views.revenue_profit_page, name="revenue_profit_page"),
    path("omzet/per-seizoen", views.revenue_season_page, name="revenue_season_page"),
    path("spaarpot", views.spaarpot_page, name="spaarpot_page"),
    path("trainersvergoedingen", views.trainer_fees_home_page, name="trainer_fees_home_page"),
    path("profiel", views.personal_profile_page, name="personal_profile_page"),
    path("trainers", views.trainers_page, name="trainers_page"),
    path("agenda", views.agenda_page, name="agenda_page"),
    path("draaiboeken", views.draaiboeken_page, name="draaiboeken_page"),
    path("voetbaldagen", views.football_days_page, name="football_days_page"),
    path("voetbaldagen/nieuw", views.football_days_new_page, name="football_days_new_page"),
    path("voetbaldagen/<int:playbook_id>", views.football_days_edit_page, name="football_days_edit_page"),
    path("samenwerkende-amateurclubs", views.amateur_clubs_page, name="amateur_clubs_page"),
    path("samenwerkende-amateurclubs/nieuw", views.amateur_clubs_new_page, name="amateur_clubs_new_page"),
    path(
        "samenwerkende-amateurclubs/<int:playbook_id>/dupliceren",
        views.amateur_clubs_duplicate_page,
        name="amateur_clubs_duplicate_page",
    ),
    path("samenwerkende-amateurclubs/<int:playbook_id>", views.amateur_clubs_edit_page, name="amateur_clubs_edit_page"),
    path("oefenstof", views.oefenstof_page, name="oefenstof_page"),
    path("oefeningen-bibliotheek", views.oefeningen_bibliotheek_page, name="oefeningen_bibliotheek_page"),
    path("oefeningen-videos", views.exercise_videos_page, name="exercise_videos_page"),
    path("trainingen", views.trainingen_page, name="trainingen_page"),
    path("trainingen/opgeslagen", views.trainingen_saved_page, name="trainingen_saved_page"),
    path("trainingen/maker", views.trainingen_maker_page, name="trainingen_maker_page"),
    path("api/trainingen", views.api_save_training, name="api_save_training"),
    path(
        "api/oefeningen-bibliotheek/category",
        views.api_update_exercise_category,
        name="api_update_exercise_category",
    ),
    path(
        "api/oefeningen-bibliotheek/update",
        views.api_update_exercise,
        name="api_update_exercise",
    ),
    path(
        "api/oefeningen-bibliotheek/field-image",
        views.api_update_exercise_field_image,
        name="api_update_exercise_field_image",
    ),
    path(
        "api/oefeningen-bibliotheek/field-overlay",
        views.api_update_exercise_field_overlay,
        name="api_update_exercise_field_overlay",
    ),
    path(
        "api/oefeningen-bibliotheek/video",
        views.api_update_exercise_video,
        name="api_update_exercise_video",
    ),
    path(
        "api/oefeningen-bibliotheek/video/delete",
        views.api_delete_exercise_video,
        name="api_delete_exercise_video",
    ),
    path(
        "api/oefeningen-bibliotheek/delete",
        views.api_delete_exercise,
        name="api_delete_exercise",
    ),
    path("voorstellen-maker", views.voorstellen_maker_page, name="voorstellen_maker_page"),
    path("voorstellen-maker/<int:proposal_id>", views.voorstellen_maker_detail_page, name="voorstellen_maker_detail_page"),
    path(
        "api/voorstellen-maker/training-counts",
        views.api_voorstellen_maker_training_counts,
        name="api_voorstellen_maker_training_counts",
    ),
    path("overeenkomsten", views.overeenkomsten_page, name="overeenkomsten_page"),
    path("overeenkomsten/nieuw", views.overeenkomsten_new_page, name="overeenkomsten_new_page"),
    path("overeenkomsten/<int:contract_id>", views.overeenkomsten_edit_page, name="overeenkomsten_edit_page"),
    path("overeenkomsten/<int:contract_id>/export-pdf", views.overeenkomsten_export_pdf, name="overeenkomsten_export_pdf"),
    path("overeenkomsten/<int:contract_id>/export-docx", views.overeenkomsten_export_docx, name="overeenkomsten_export_docx"),
    path("marketing", views.marketing_page, name="marketing_page"),
    path("social-media", views.social_media_page, name="social_media_page"),
    path("content", views.content_page, name="content_page"),
    path("content/<int:album_id>", views.content_album_page, name="content_album_page"),
    path("api/orders", views.api_orders, name="api_orders"),
    path("api/v1/agenda/events", views.api_agenda_events, name="api_agenda_events"),
    path("api/v1/agenda/calendar.ics", views.api_agenda_calendar, name="api_agenda_calendar"),
    path("api/dashboard-summary", views.api_dashboard_summary, name="api_dashboard_summary"),
    path("api/products/search", views.api_product_search, name="api_product_search"),
    path("api/products/registration-count", views.api_product_registration_count, name="api_product_registration_count"),
    path(
        "api/voetbaldagen/registration-counts",
        views.api_football_days_registration_counts,
        name="api_football_days_registration_counts",
    ),
    path(
        "api/voetbaldagen/export-pdf",
        views.api_football_days_export_pdf,
        name="api_football_days_export_pdf",
    ),
    path(
        "api/samenwerkende-amateurclubs/registration-counts",
        views.api_amateur_clubs_registration_counts,
        name="api_amateur_clubs_registration_counts",
    ),
    path(
        "api/samenwerkende-amateurclubs/export-pdf",
        views.api_amateur_clubs_export_pdf,
        name="api_amateur_clubs_export_pdf",
    ),
    path("api/dashboard-events", views.api_dashboard_events, name="api_dashboard_events"),
    path(
        "api/registrations/email-status",
        views.api_update_registration_email_status,
        name="api_update_registration_email_status",
    ),
    path(
        "api/registrations/event-email-settings",
        views.api_save_registration_event_email_settings,
        name="api_save_registration_event_email_settings",
    ),
    path(
        "api/registrations/send-event-email",
        views.api_send_registration_event_email,
        name="api_send_registration_event_email",
    ),
    path(
        "api/registrations/sync-emailed-orders",
        views.api_sync_emailed_registration_orders,
        name="api_sync_emailed_registration_orders",
    ),
    path(
        "api/registrations/event-completed",
        views.api_complete_registration_event,
        name="api_complete_registration_event",
    ),
    path(
        "api/registrations/event-canceled",
        views.api_cancel_registration_event,
        name="api_cancel_registration_event",
    ),
    path(
        "api/leads/blocked-emails",
        views.api_save_leads_blocked_emails,
        name="api_save_leads_blocked_emails",
    ),
    path("api/push/status", views.api_push_status, name="api_push_status"),
    path("api/push/subscribe", views.api_push_subscribe, name="api_push_subscribe"),
    path("api/push/unsubscribe", views.api_push_unsubscribe, name="api_push_unsubscribe"),
    path("api/dashboard-weather", views.api_dashboard_weather, name="api_dashboard_weather"),
    path("api/agenda-school-holidays", views.api_agenda_school_holidays, name="api_agenda_school_holidays"),
    path("api/agenda-public-holidays", views.api_agenda_public_holidays, name="api_agenda_public_holidays"),
    path("manifest.webmanifest", views.web_manifest, name="web_manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")
